ServerCore/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerCore.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ServerCore/Pages/EventIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerCore.ModelBases;

namespace ServerCore.Pages
{
    public class EventIndexModel : EventSpecificPageModel { }
}

ServerCore/Pages/EventLandingPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerCore.DataModel;
using ServerCore.ModelBases;

namespace ServerCore.Pages
{
    public class EventLandingPageModel : EventSpecificPageModel
    {
        private readonly PuzzleServerContext _context;

        public EventLandingPageModel(PuzzleServerContext context)
        {
            _context = context;
        }
        public void OnGet()
        {

        }
    }
}

ServerCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerCore.Pages
{
    [AllowAnonymous]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ServerCore/Pages/TestConfig.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerCore.Pages
{
    [Authorize(Policy = "IsGlobalAdmin")]
    public class TestConfigModel : PageModel
    {
        public IActionResult OnPostSendTestEmail()
        {
            // The purpose of this function is to verify that the server is configured properly.
            // That's why there are no options and we don't try different kinds of recipients and bodies.
            // The one exception is including a hyperlink in the test mail so we can verify linkifying
            // happens in various email clients.
            if (MailHelper.Singleton == null)
            {
                return StatusCode(500, "MailHelper was not initialized.");
            }
            MailHelper.Singleton.SendPlaintextBcc(
                new List<string> { "puzztech@service.microsoft.com" },
                "This is a test from PuzzleServer",
                "This test is from https://github.com/PuzzleServer/mainpuzzleserver");
            if (!MailHelper.Singleton.Enabled)
            {
                return StatusCode(500, "MailHelper was initialized, but not configured properly. Mail sent to debug output.");
            }
            return RedirectToPage();
        }
    }
}

ServerCore/Pages/EventIndex.cshtml
@page "/{eventId}"
@model ServerCore.Pages.EventIndexModel
@{
    ViewData["Title"] = "EventIndex";
}

<h2>@Model.Event.Name</h2>

ServerCore/Pages/EventLandingPage.cshtml
@page "/Event/{eventId}"
@model ServerCore.Pages.EventLandingPageModel

<h1>@Model.Event.Name</h1>

ServerCore/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Microsoft Puzzle Event Homepage";
}

<h3>Upcoming events</h3>

<h4>Microsoft Non-Intern Puzzleday 2025</h4>
<a href="https://puzzlehunt.azurewebsites.net/nipd2025/play">
    <img src="~/images/pd2025/nipd2025logo.png" width="450" title="Non-Intern Puzzleday 2025 logo" alt="Non-Intern Puzzleday 2025 logo, with Clippy" />
</a>
<p>A one-day rebroadcast for employees and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2025/play">Go to the Non-Intern Puzzleday event</a>

<br /><br /><br />

<h3>Past Events</h3>

<h4>Microsoft Intern Puzzleday 2025</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2025/play">Go to the Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2025</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/ps25/play">Go to the Puzzle Safari 2025 event</a>

<hr/>

<h4>Puzzlehunt 24</h4>
<p>PUZA Corp seeks spaceflight-certified crews for supply missions. Join us! This is a weekend-long event June 7-8, 2025, open to local and remote teams. Puzzles of all levels are included! </p>
<a href="https://puzzlehunt.azurewebsites.net/ph24/play">Go to the Puzzlehunt event</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2024</h4>
<p>A one-day rebroadcast for employees and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2024/play">Go to the Non-Intern Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2024</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://gamenight.solutions/">Go to the Puzzle Safari 2024 event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2024</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2024/play">Go to the Puzzleday event</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2023</h4>
<p>A one-day rebroadcast for employees and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2023/play">Go to the Non-Intern Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2023</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="http://badideas.solutions">Go to the Puzzle Safari 2023 event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2023</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2023/play">Go to the Puzzleday event</a>

<hr />

<h4>Puzzlehunt 23</h4>
<p>Puzzle University is committed to providing a modern enigmatological education, where every course is a puzzle. This is a weekend-long event May 6-7, 2023 for solvers anywhere.</p>
<a href="https://www.puzzle.university">Go to Puzzlehunt 23</a>

<hr />

<h4>Puzzlehunt 22</h4>
<p>You are cordially invited to the Grand Opening and Ribbon Cutting of the Parallax Antimatter Research Analysis Laboratory Linear Accelerator Xyclotron. This is a weekend-long event September 17-18, 2022 for FTEs and friends. Puzzles of all levels are included!</p>
<a href="https://puzzlehunt.azurewebsites.net/ph22/play">Go to Puzzlehunt 22</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2022</h4>
<p>A one-day rebroadcast for employees and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2022/play">Go to the Non-Intern Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2022</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://aka.ms/puzzlesafari22">Go to the Puzzle Safari event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2022</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2022/play">Go to the Puzzleday event</a>

<hr />

<h4>March 2022 Intern Puzzleday</h4>
<p>A two-day event over one week for interns that was replayed for the first time this spring.</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2021.2203/play">Go to the Puzzleday event</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2021</h4>
<p>A one-weekend event for FTEs and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2021/play">Go to Non-Intern Puzzleday 2021</a>

<hr />

<h4>Puzzle Safari 2021</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://aka.ms/puzzlesafari21">Go to the Puzzle Safari event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2021</h4>
<p>A two-day event over one weekend for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2021/play">Go to the Puzzleday event</a>

<hr />

<h4>Microsoft Puzzlehunt 21</h4>
<p>A weekend-long event in spring <b style="color:red">2021</b> (postponed from 2020, sorry) for full-time employees and friends. Puzzles of all levels are included!</p>
<a href="https://puzzlehunt.azurewebsites.net/ph21/play">Go to the Puzzlehunt event</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2020</h4>
<p>A one-weekend event for FTEs and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2020/play">Go to the Non-Intern Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2020</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://aka.ms/puzzlesafari20">Go to the Puzzle Safari event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2020</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2020/play">Go to the Puzzleday event</a>

<hr />

<h4>Microsoft Puzzlehunt 20</h4>
<p>A weekend-long event in spring for full-time employees and friends. Puzzles of all levels are included!</p>
<a href="https://puzzlehunt.azurewebsites.net/ph20/play">Go to the Puzzlehunt event</a>

<hr />

<h4>Microsoft Intern Puzzleday 2019</h4>
<p>A one-day event for interns and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/pd2019/play">Go to the Puzzleday event</a>

<hr />

<h4>Microsoft Non-Intern Puzzleday 2019</h4>
<p>A one-day rebroadcast for employees and friends that happens every summer. Puzzle solvers of all levels of experience are welcome!</p>
<a href="https://puzzlehunt.azurewebsites.net/nipd2019/play">Go to the Non-Intern Puzzleday event</a>

<hr />

<h4>Puzzle Safari 2019</h4>
<p>A one-day event for employees and friends that combines solving, running, and searching. Puzzle solvers at all levels are welcome!</p>
<a href="https://aka.ms/puzzlesafari">Go to the Puzzle Safari event</a>

ServerCore/Pages/TestConfig.cshtml
@page "/testconfig"
@model ServerCore.Pages.TestConfigModel
@{
}
<style>
    button:disabled {
        color: #aaaaaa;
    }
</style>
<script>
    function confirmSendTest() {
        var t = confirm('Are you sure you want to send a real test email to puzztech@service.microsoft.com?');
        document.getElementById('SendTestEmail').disabled = t;
        return t;
    }
</script>
<h2>Test Configuration</h2>

<p>This page is used to test server configuration. It is only for sysadmins.</p>

<form method="post" style="display:inline-block" onsubmit="return confirmSendTest()">
    <button type="submit" id="SendTestEmail"
            asp-page-handler="SendTestEmail"
            style="margin-left: 5px; margin-right: 5px;">
        Send Test Email
    </button>
</form>